ARG EX_VSN=1.16.0
ARG OTP_VSN=26.2.1
ARG DEB_VSN=bullseye-20231009-slim
ARG BUILDER_IMG="hexpm/elixir:${EX_VSN}-erlang-${OTP_VSN}-debian-${DEB_VSN}"

FROM ${BUILDER_IMG}

# Install Git
RUN apt-get update && \
    apt-get install -y git inotify-tools && \
    rm -rf /var/lib/apt/lists/*

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

# Set up IEx history
RUN echo '\nhistory_file = Path.expand("~/.iex_history")' >> ~/.iex.exs

# We'll run mix deps.get when we start the container, not during build
CMD ["mix", "deps.get", "&&", "mix", "phx.server"]